#! /usr/bin/env bash

#
# Install Brew Dependencies
#
# Example:
#
#   brew_install work
#

set -eu -o pipefail

function fail() {
    echo "Must supply 'personal' or 'work' as an argument"
    exit 1
}

if [ "${#}" -ne 1 ]; then
    fail
fi

TYPE=$1

if [ "${TYPE}" != "personal" ] && [ "${TYPE}" != "work" ]; then
    fail
fi

while IFS= read -r tap; do brew tap "${tap}"; done < "brew_tap_${TYPE}.txt"

while IFS= read -r pkg; do brew install "${pkg}"; done < "brew_${TYPE}.txt"
