#! /usr/bin/env bash

if [ "$(uname)" == 'Linux' ]; then
    alias ps='ps auxf'
    alias ls='ls -alh --color=auto'
else
    alias ps='ps aux'
    alias ls='ls -h'
    alias ip="ifconfig en0 | grep 'inet ' | cut -d' ' -f 2"
    alias sethostname='scutil –set HostName'
    alias lock='/System/Library/CoreServices/"Menu Extras"/User.menu/Contents/Resources/CGSession -suspend'
    alias fsleep="osascript -e 'tell the application \"Finder\" to sleep'"
    alias screensaver="/System/Library/Frameworks/ScreenSaver.framework/Resources/ScreenSaverEngine.app/Contents/MacOS/ScreenSaverEngine"

    # This requires the directory of the app you wish to unquarantine
    # $ xrelease /Applications/Adium.app/
    alias xrelease="sudo xattr -d -r com.apple.quarantine"

    # show and hide hidden files
    alias showfiles="defaults write com.apple.Finder AppleShowAllFiles TRUE; killall Finder"
    alias hidefiles="defaults write com.apple.Finder AppleShowAllFiles FALSE; killall Finder"

    # Clear DNS
    alias cleardns="sudo killall -HUP mDNSResponder"
    #alias cleardns="sudo discoveryutil udnsflushcaches"

    # Disable warnings about pyenv with brew
    alias brew='env PATH="${PATH//$(pyenv root)\/shims:/}" brew'

    # VS Code
    # press and hold means I can't use vim extensions properly in vs code
    alias vscode_disable_pressandhold="defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false"
    alias vscode_enable_pressandhold="defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool true"
fi

# common
alias h="history"
alias s="source ~/.bash_profile"
alias ll='exa --all --long --header --group --git --links --group-directories-first --color-scale --time-style=long-iso'
alias now="date +'%F %T'"
alias rand="tr -dc 'a-zA-Z0-9' < /dev/urandom | fold -w 32 | head -n 1"

# GPG
alias gpg_list_keys="gpg --list-secret-keys --keyid-format=long"

# tar files
alias maketar='tar -pczf'
alias untar='tar -xvf'

# python
alias simpleserver='python -m SimpleHTTPServer 8000'
alias d="deactivate"

# git
alias gi='git'
alias gpr='open "https://$(git_current_domain)/$(git_current_origin)/pull/new/$(git_current_branch)"'
alias glpr='open "https://$(git_current_domain)/$(git_current_origin)/-/merge_requests/new?merge_request%5Bsource_branch%5D=$(git_current_branch)"'
alias gcompare='open "http://$(git_current_domain)/$(git_current_origin)/compare/$(git_ref_origin)...$(git_ref_head)"'
alias gpull='git pull origin $(git_branch_name)'
alias gcm='git checkout main || git checkout master'

